name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env << EOF
          DATABASE_URL=mongodb://localhost:27017
          SMTP_SERVER=smtp.gmail.com
          SMTP_USERNAME=test@example.com
          SMTP_PASSWORD="aaaa aaaa aaaa aaaa"
          
          EMAIL_USER=test@example.com
          EMAIL_PASSWORD="aaaa aaaa aaaa aaaa"
          EMAIL_HOST=imap.gmail.com
          EMAIL_PORT=993
          
          SECRET_KEY=this_is_a_secret_key
          ENCRYPTION_KEY=total_secret_key 
          EOF
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
          
      - name: Build
        run: cargo build --verbose
        
      - name: Run tests
        run: cargo test --verbose
